[package]
name = "back"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
solana-client = "1.18.11"
solana-sdk = "1.18.11"
spl-token = "4.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
