import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Providers } from "./providers";
import { AlertTriangle } from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function BackendWarning() {
  return (
    <div className="fixed top-4 right-4 z-50">
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" className="mt-[100px] bg-yellow-100">
            <AlertTriangle className="h-4 w-4 mr-2 text-yellow-500" />
            Backend Status
            <Badge
              variant="destructive"
              className="absolute -top-2 -right-2 h-5 w-5 p-0 flex items-center justify-center bg-zinc-600 z-99"
            >
              What
            </Badge>
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-80">
          <div className="p-4 space-y-2">
            <div className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-yellow-500" />
              <h4 className="font-semibold">Backend Unavailable</h4>
            </div>
            <p className="text-sm text-gray-500">
              This application is currently running in a hosted environment
              where the backend is not available. Please contact Ashish for the
              backend code to run the application locally.
            </p>
            <div className="pt-2">
              <Button variant="outline" className="w-full" asChild>
                <a href="mailto:hi@ashish.services" className="text-sm">
                  Contact Ashish
                </a>
              </Button>
            </div>
          </div>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/@solana/web3.js@latest/lib/index.iife.min.js"></script>
      </head>
      <body className="antialiased">
        <Providers>
          <BackendWarning />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
